spring:
  batch:
    job:
      enabled: false # Désactive le lancement automatique des jobs
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/horoquartz_batch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.batch: DEBUG
    com.example.horoquartz: DEBUG
